### ISSUE TITLE
Pool of source sheets instead of infinite strip of fixed width.

### ISSUE THREAD

**Issue by SlausB** [rdarder/guillotine#1]
Hello. Awesome library.
Is there a way to define an are as an [infinite] pool of source sheets (width width and height) instead of trying to layout to single source sheet of fixed width?
Thanks in advance.

**Comment by rdarder** [comment]
Hey there, unfortunately this implementation works with a fixed with - infinite height single source sheet. It would be somewhat straightforward to do multiple same-width sheets (changing the cost function), but multiple custom source sheets implies a larger refactor. 
I think it's a very good use case, and I found myself needing it from time to time. I won't have time to do this in the near future, PR's are welcome though. 
I'll keep this in mind as I'm (intermitently) developing an alternative approach to gcuts. Thanks!
